name: Test on Cygwin
on: push

jobs:
  cygwin_build_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3000
      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          install-dir: 'C:\tools\cygwin'
          packages: >-
            python38-numpy python38-devel python38-dateutil
            python38-pytz python38-cython gcc-core gcc-g++
            python38-html5lib python38-hypothesis python38-jinja2
            python38-lxml python38-matplotlib python38-pytest
            python38-requests git cmake
      - name: Set Windows PATH
        uses: egor-tensin/cleanup-path@v1
        with:
          dirs: 'C:\tools\cygwin\bin;C:\tools\cygwin\lib\lapack'
      - name: Checkout with Cygwin git
        run: |
          C:\tools\cygwin\bin\dash -c '/usr/bin/git checkout HEAD'
      - name: Install build and test dependencies
        run: |
          dash -c "/usr/bin/python3.8 -m pip install sphinx-theme-builder scikit-build"
          dash -c "/usr/bin/grep -v -F -e statsmodels requirements-dev.txt >requirements-install.txt"
          dash -c "/usr/bin/python3.8 -m pip install --no-build-isolation -r requirements-install.txt"
      - name: Build Pandas wheel
        run: |
          dash -c "/usr/bin/python3.8 setup.py bdist_wheel"
      - name: Install the new Pandas wheel
        run: |
          dash -c "/usr/bin/python3.8 -m pip install dist/pandas-*cp38*.whl"
      - name: Run Pandas test suite
        run: |
          dash test_fast.sh
