name: Test on Cygwin
on: push

jobs:
  cygwin_build_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 6000
      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          install-dir: 'C:\tools\cygwin'
          packages: >-
            python38-numpy python38-devel python38-dateutil
            python38-pytz python38-cython gcc-core gcc-g++
            python38-html5lib python38-hypothesis python38-jinja2
            python38-lxml python38-matplotlib python38-pytest
            python38-requests git cmake liblapack-devel libhdf5-devel
            python38-cryptography python38-zmq python38-ipython
            libsnappy-devel libiconv-devel dos2unix alternatives
      - name: Set Windows PATH
        uses: egor-tensin/cleanup-path@v1
        with:
          dirs: 'C:\tools\cygwin\bin;C:\tools\cygwin\lib\lapack'
      - name: Install build and test dependencies
        run: |
          dash -c "/usr/bin/python3.8 -m pip install sphinx-theme-builder scikit-build pybind11"
          dash -c "/usr/bin/grep -v -F -e statsmodels -e scipy -e numba -e fastparquet -e pyarrow -e xarray -e seaborn -e blosc -e tables -e boto -e s3 -e pyreadstat -e parquet requirements-dev.txt >requirements-install.txt"
          dash -c "/usr/bin/python3.8 -m pip install --no-build-isolation -r requirements-install.txt"
      - name: Build Pandas wheel
        run: |
          dash -c "/usr/bin/python3.8 setup.py bdist_wheel"
      - name: Install the new Pandas wheel
        run: |
          dash -c "/usr/bin/python3.8 -m pip install dist/pandas-*cp38*.whl"
      - name: Make pytest-3.8 available as pytest
        run: |
          dash -c "/usr/sbin/alternatives --install /usr/bin/pytest pytest /usr/bin/pytest-3.8 38"
      - name: Run Pandas test suite
        run: |
          dash -c "/usr/bin/dos2unix test_fast.sh"
          dash -c "mkdir run_tests"
          dash -c "cd run_tests; bash ../test_fast.sh 3.8
